name: Deploy to staging

on:
  push:
    branches: [ git-actions-test ]

env:
  SSH_HOST: ${{ secrets.STAGING_HOST }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  SSH_PORT: ${{ secrets.SSH_PORT }}
  GITHUB_SHA: ${{ github.sha }}
  HOME_PATH: ${{ secrets.STAGING_BASE_PATH }}
  RELEASES_PATH: ${{ secrets.STAGING_BASE_PATH }}/releases
  STORAGE_PATH: ${{ secrets.STAGING_BASE_PATH }}/storage
  ARTIFACTS_PATH: ${{ secrets.STAGING_BASE_PATH }}/artifacts
  LATEST_RELEASE_PATH: ${{ secrets.STAGING_BASE_PATH }}/releases/${{ github.sha }}
  PUBLIC_HTML_PATH: ${{ secrets.STAGING_BASE_PATH }}/public_html
  ACTIVE_PATH: ${{ secrets.STAGING_BASE_PATH }}/public_html/current
  LARAVEL_PUBLIC_PATH: ${{ secrets.STAGING_BASE_PATH }}/public_html/current/public
  ENV: ${{ secrets.STAGING_ENV }}
  PHP_PATH: /usr/local/bin/php81

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    outputs:
      deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and Javascript
        run: |
          npm install
          npm run prod
      - name: Add storage dir
        run: |
          rm -rf "storage"
          mkdir -p storage/app
          mkdir -p storage/logs
          mkdir -p storage/public
          mkdir -p storage/logs
          mkdir -p storage/framework
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/testing
          mkdir -p storage/framework/views
          chmod -R 0777 storage

      - name: Composer install
        run: composer install --no-dev --no-interaction --prefer-dist
      - name: Create deployment artifact
        run: tar --create --gzip --file="${{ env.GITHUB_SHA }}.tar.gz" --exclude-vcs --exclude-vcs-ignores * .htaccess*
      - name: Store artifact for distribution
        uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: "${{ env.GITHUB_SHA }}.tar.gz"

  prepare-release-on-servers:
    name: "Staging server: Prepare release"
    runs-on: ubuntu-latest
    needs: create-deployment-artifacts
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: app-build
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: "${{ env.SSH_HOST }}"
          username:  "${{ env.SSH_USERNAME }}"
          passphrase: "${{ env.SSH_PASSPHRASE }}"
          key: "${{ env.SSH_KEY }}"
          port: "${{ env.SSH_PORT }}"
          source: "${{ env.GITHUB_SHA }}.tar.gz"
          target: "${{ env.ARTIFACTS_PATH }}"

      - name: Extract archive and create directories
        uses: appleboy/ssh-action@master
        with:
          host: "${{ env.SSH_HOST }}"
          username: "${{ env.SSH_USERNAME }}"
          passphrase: "${{ env.SSH_PASSPHRASE }}"
          key: "${{ env.SSH_KEY }}"
          port: "${{ env.SSH_PORT }}"
          script: |
            mkdir -p "${{ env.HOME_PATH }}/releases"
            mkdir -p "${{ env.HOME_PATH }}/public_html"
            mkdir -p "${{ env.HOME_PATH }}/artifacts"
            mkdir -p "${{ env.RELEASES_PATH }}/${{ env.GITHUB_SHA }}"
            mkdir -p "${{ env.ACTIVE_PATH }}"
            tar --extract --ungzip --file="${{ env.ARTIFACTS_PATH }}/${{ env.GITHUB_SHA }}.tar.gz" --directory="${{ env.LATEST_RELEASE_PATH }}"
            rm -rf "${{ env.STORAGE_PATH }}"
            mkdir -p "${{ env.STORAGE_PATH }}/app"
            mkdir -p "${{ env.STORAGE_PATH }}/logs"
            mkdir -p "${{ env.STORAGE_PATH }}/public"
            mkdir -p "${{ env.STORAGE_PATH }}/logs"
            mkdir -p "${{ env.STORAGE_PATH }}/framework"
            mkdir -p "${{ env.STORAGE_PATH }}/framework/cache"
            mkdir -p "${{ env.STORAGE_PATH }}/framework/sessions"
            mkdir -p "${{ env.STORAGE_PATH }}/framework/testing"
            mkdir -p "${{ env.STORAGE_PATH }}/framework/views"
            chmod -R 0777 "${{ env.STORAGE_PATH }}"

  activate-release:
    name: "Staging server: Activate release"
    runs-on: ubuntu-latest
    needs: prepare-release-on-servers
    steps:
      - name: Activate release
        uses: appleboy/ssh-action@master
        with:
          host: "${{ env.STAGING_HOST }}"
          username: "${{ env.SSH_USERNAME }}"
          passphrase: "${{ env.SSH_PASSPHRASE }}"
          key: "${{ env.SSH_KEY }}"
          port: "${{ env.SSH_PORT }}"
          script: |
            printf "%s" "${{ env.ENV }}" > "${{ env.HOME_PATH }}/.env.staging"
            ln --symbolic --force "${{ env.HOME_PATH }}/.env.staging" "${{ env.LATEST_RELEASE_PATH }}/.env"
            cd "${{ env.PUBLIC_HTML_PATH }}"
            ln --symbolic "${{ env.STORAGE_PATH }}" "${{ env.ACTIVE_PATH }}"
            ln --symbolic --force --no-dereference "${{ env.LATEST_RELEASE_PATH }}" current
            ln --symbolic --force --no-target-directory "${{ env.ACTIVE_PATH }}/.htaccess-siteground-public_html" .htaccess
            cd "${{ env.LARAVEL_PUBLIC_PATH }}"
            ln --symbolic --force --no-target-directory "${{ env.ACTIVE_PATH }}/.htaccess-siteground-public" .htaccess

  run-after-hooks:
    name: "Staging server: After hook"
    runs-on: ubuntu-latest
    needs: activate-release
    steps:
      - name: Run after hooks
        uses: appleboy/ssh-action@master
        with:
          host: "${{ env.STAGING_HOST }}"
          username: "${{ env.SSH_USERNAME }}"
          passphrase: "${{ env.SSH_PASSPHRASE }}"
          key: "${{ env.SSH_KEY }}"
          port: "${{ env.SSH_PORT }}"
          script: |
            cd "${{ env.ACTIVE_PATH }}"
            "${{ env.PHP_PATH }}" artisan migrate --no-interaction --force

  clean-up:
    name: "Staging server: Clean up"
    runs-on: ubuntu-latest
    needs: run-after-hooks
    steps:
      - name: Run after hooks
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          passphrase: ${{ env.SSH_PASSPHRASE }}
          key: ${{ env.SSH_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd "${{ env.RELEASES_PATH }}" && ls -t -1 | tail -n +1 | xargs rm -rf
            cd "${{ env.ARTIFACTS_PATH }}" && ls -t -1 | tail -n +1 | xargs rm -rf
