name: Deploy to staging

on:
  push:
    branches: [ git-actions-test ]

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    outputs:
      deployment-matrix: ${{ steps.export-deployment-matrix.outputs.deployment-matrix }}
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and Javascript
        run: |
          npm install
          npm run prod

      - name: Create storage directories
        run: |
          mkdir -p storage/{app,framework,logs}
          mkdir -p storage/framework/{cache,session,views}
          chmod -R 777 storage

      - name: Composer install
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git --exclude=node_modules --exclude=.nyc_output --exclude=tests *

      - name: Store artifact for distribution
        uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz

  prepare-release-on-servers:
    name: "Staging server: Prepare release"
    runs-on: ubuntu-latest
    needs: create-deployment-artifacts
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: app-build
      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ${{ github.sha }}.tar.gz
          target: ${{ secrets.STAGING_BASE_PATH }}/artifacts

      - name: Extract archive and create directories
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_SHA
          script: |
            mkdir -p ${{ secrets.STAGING_BASE_PATH }}/{releases,public_html,artifacts}
            mkdir -p "${{ secrets.STAGING_BASE_PATH }}/releases/${GITHUB_SHA}"
            mkdir -p "${{ secrets.STAGING_BASE_PATH }}/public_html/current"
            tar xzf ${{ secrets.STAGING_BASE_PATH }}/artifacts/${GITHUB_SHA}.tar.gz -C "${{ secrets.STAGING_BASE_PATH }}/releases/${GITHUB_SHA}"
            rm -rf ${{ secrets.STAGING_BASE_PATH }}/releases/${GITHUB_SHA}/storage
            mkdir -p ${{ secrets.STAGING_BASE_PATH }}/storage/{app,public,framework,logs}
            mkdir -p ${{ secrets.STAGING_BASE_PATH }}/storage/framework/{cache,sessions,testing,views}
            chmod -R 0777 ${{ secrets.STAGING_BASE_PATH }}/storage

  run-before-hooks:
    name: "Staging server: Before hook"
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-servers ]
    steps:
      - name: Run before hooks
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ secrets.STAGING_BASE_PATH }}/releases/${{ github.sha }}
          CURRENT_RELEASE_PATH: ${{ secrets.STAGING_BASE_PATH }}/current
          STORAGE_PATH: ${{ secrets.STAGING_BASE_PATH }}/storage
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_SHA,RELEASE_PATH,CURRENT_RELEASE_PATH,STORAGE_PATH,STAGING_BASE_PATH
          script: |
            ${{ matrix.server.beforeHooks }}

  activate-release:
    name: "Staging server: Activate release"
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-servers, run-before-hooks ]
    steps:
      - name: Activate release
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ secrets.STAGING_BASE_PATH }}/releases/${{ github.sha }}
          PUBLIC_HTML_PATH: ${{ secrets.STAGING_BASE_PATH }}/public_html
          CURRENT_RELEASE_PATH: ${{ secrets.STAGING_BASE_PATH }}/public_html/current
          PUBLIC_PATH: $CURRENT_RELEASE_PATH/public
          STORAGE_PATH: ${{ secrets.STAGING_BASE_PATH }}/storage
          STAGING_BASE_PATH: ${{ secrets.STAGING_BASE_PATH }}
          STAGING_ENV: ${{ secrets.STAGING_ENV }}
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_SHA,RELEASE_PATH,PUBLIC_HTML_PATH,CURRENT_RELEASE_PATH,PUBLIC_PATH,STORAGE_PATH,STAGING_BASE_PATH,STAGING_ENV
          script: |
#             Put Laravel in maintenance mode
#            mkdir -p $CURRENT_RELEASE_PATH
#            cd $CURRENT_RELEASE_PATH
#            /usr/local/bin/php81 artisan down

            # Persist environment
            printf "%s" "$STAGING_ENV" > "${RELEASE_PATH}/.env"

            # Create a new [forced] link to the latest release as "current"
            cd $PUBLIC_HTML_PATH
            ln --symbolic --force $RELEASE_PATH current

            # Create a link to the global storage in the new release dir
            cd $CURRENT_RELEASE_PATH
            ln --symbolic --force $STORAGE_PATH

            cd $CURRENT_PATH
            # Create a link called "current" pointing to the latest release
            ln --symbolic --force $PUBLIC_HTML_PATH $CURRENT_RELEASE_PATH
            ln -s -f $CURRENT_RELEASE_PATH/.htaccess-siteground-public_html $PUBLIC_HTML_PATH/.htaccess
            ln -s -f $CURRENT_RELEASE_PATH/.htaccess-siteground-public $PUBLIC_PATH/.htaccess

  run-after-hooks:
    name: "Staging server: After hook"
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-servers, run-before-hooks, activate-release ]
    steps:
      - name: Run after hooks
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
          RELEASE_PATH: ${{ secrets.STAGING_BASE_PATH }}/releases/${{ github.sha }}
          PUBLIC_HTML_PATH: ${{ secrets.STAGING_BASE_PATH }}/public_html
          CURRENT_RELEASE_PATH: $PUBLIC_HTML_PATH/current
          PUBLIC_PATH: $CURRENT_RELEASE_PATH/public
          STORAGE_PATH: ${{ secrets.STAGING_BASE_PATH }}/storage
          STAGING_BASE_PATH: ${{ secrets.STAGING_BASE_PATH }}
          STAGING_ENV: ${{ secrets.STAGING_ENV }}
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_SHA,RELEASE_PATH,PUBLIC_HTML_PATH,CURRENT_RELEASE_PATH,PUBLIC_PATH,STORAGE_PATH,STAGING_BASE_PATH,STAGING_ENV
          script: |
            cd $CURRENT_RELEASE_PATH
            php81 artisan migrate

  clean-up:
    name: "Staging server: Clean up"
    runs-on: ubuntu-latest
    needs: [ create-deployment-artifacts, prepare-release-on-servers, run-before-hooks, activate-release, run-after-hooks ]
    steps:
      - name: Run after hooks
        uses: appleboy/ssh-action@master
        env:
          RELEASES_PATH: ${{ secrets.STAGING_BASE_PATH }}/releases
          ARTIFACTS_PATH: ${{ secrets.STAGING_BASE_PATH }}/artifacts
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: RELEASES_PATH,ARTIFACTS_PATH
          script: |
            cd $RELEASES_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
            cd $ARTIFACTS_PATH && ls -t -1 | tail -n +6 | xargs rm -rf
